sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t duncdrum/exist-docker .
  - docker run -it -d --name exist -p 8080:8080 duncdrum/exist-docker
script:
  - docker exec exist java -version
  - docker exec exist java -Dexist.home=/exist -jar /exist/start.jar client --no-gui --local --xpath "system:get-version()"
  - docker logs exist
  - docker ps -a
