image:
  - Visual Studio 2017
  - Ubuntu

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  before_build:
  - ps: $Env:LCOW_SUPPORTED=1
  - ps: $Env:LCOW_API_PLATFORM_IF_OMITTED="linux"
  - ps: Restart-Service Docker

build_script:
  - docker build -t duncdrum/exist-docker .
  - docker run -it -d --name exist -p 8080:8080 duncdrum/exist-docker

before_test:
  - sleep 35

test_script:
  - docker exec exist java -version
  - docker logs exist
  - docker ps -a
